# Dockerfile for the COMET Spatial Pipeline (image: spatial_pipeline:v1).
# Built via `docker compose build` / `docker compose up --build`, driven by
# docker-compose.yml in this same folder. This file must live in the repo
# (not just as a locally-saved image/tar) so the image can be reproduced from
# source alone.
#
# Use a stable Ubuntu base to support both Python and R cleanly
FROM ubuntu:22.04

# Prevent interactive prompts during package installations
ENV DEBIAN_FRONTEND=noninteractive

# Install system dependencies required for spatial computing, graphics, and R compiling
RUN apt-get update && apt-get install -y --no-install-recommends \
    wget \
    curl \
    git \
    ca-certificates \
    build-essential \
    libgl1-mesa-glx \
    libglib2.0-0 \
    gfortran \
    liblapack-dev \
    libopenblas-dev \
    libxml2-dev \
    libssl-dev \
    libcurl4-openssl-dev \
    && rm -rf /var/lib/apt/lists/*

# Install Miniforge3 (which natively includes Mamba) to manage our unified bioinformatics stack
RUN wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh -O miniforge.sh \
    && bash miniforge.sh -b -p /opt/conda \
    && rm miniforge.sh

# Put conda/mamba in the system path environment
ENV PATH=/opt/conda/bin:$PATH

# Configure channels for reproducible bioinformatics resolving
RUN conda config --add channels defaults \
    && conda config --add channels bioconda \
    && conda config --add channels conda-forge \
    && conda config --set channel_priority strict

# Install exact Python and spatial math library foundations from your Mac history
RUN mamba install -y \
    python=3.10 \
    numpy=1.26 \
    scipy=1.11 \
    scikit-image \
    squidpy=1.6.5 \
    snakemake \
    && mamba clean --all -y

# Install R and Seurat directly via Mamba to guarantee binary library alignments.
# Pinned to match envs/harpy_r_env.yaml (the macOS reference env) exactly: the
# R script generated by the Snakefile's convert_to_seurat rule calls
# SetAssayData(..., layer = "data", ...), which is Seurat v5-only syntax
# (SeuratObject >=5.0 renamed the "slot" argument to "layer"). Seurat 4.x does
# not accept a `layer` argument and would fail this step with
# "unused argument (layer = ...)" — so this pin must not drift below 5.x.
RUN mamba install -y \
    r-base=4.4 \
    r-seurat=5.1.0 \
    r-matrix=1.7_5 \
    && mamba clean --all -y

# Install exact PyPI spatial and dashboard packages from your Mac environment
RUN pip install --no-cache-dir \
    anndata==0.11.4 \
    streamlit==1.58.0 \
    harpy-analysis==0.3.0

# Expose the standard port used by your Streamlit interactive cell-type assignment interface
EXPOSE 8501

# Set up a working directory mapping inside the container
WORKDIR /data

# Default action when launching the container is a bash terminal prompt
CMD ["/bin/bash"]