#!/usr/bin/env python3
"""
launch_pipeline_gui.py

Windows GUI launcher for the COMET Spatial Pipeline.
Double-click RUN_COMET_PIPELINE.BAT to open this window.

This file lives in the root of the pipeline git repository,
alongside docker-compose.yml and the Snakefile.
"""

import os
import re
import sys
import time
import shutil
import platform
import subprocess
import threading
import webbrowser

try:
    import tkinter as tk
    from tkinter import ttk, filedialog, messagebox, scrolledtext
except ImportError:
    sys.exit(
        "ERROR: tkinter is not available.\n"
        "On Windows, reinstall Python from https://www.python.org/ and make sure\n"
        "'tcl/tk and IDLE' is checked during installation."
    )

# ---------------------------------------------------------------------------
# Path resolution
# ---------------------------------------------------------------------------
# This script lives in the repo root alongside docker-compose.yml.
SCRIPT_DIR   = os.path.dirname(os.path.abspath(__file__))
COMPOSE_FILE = os.path.join(SCRIPT_DIR, "docker-compose.yml")

# Common install locations for Docker Desktop on Windows.
_DOCKER_DESKTOP_CANDIDATES = [
    os.path.join(
        os.environ.get("ProgramFiles", r"C:\Program Files"),
        "Docker", "Docker", "Docker Desktop.exe",
    ),
    os.path.join(
        os.environ.get("LOCALAPPDATA", ""),
        "Programs", "Docker", "Docker", "Docker Desktop.exe",
    ),
]

DOCKER_READY_TIMEOUT = 120   # seconds to wait for Docker to become ready

# ---------------------------------------------------------------------------
# Theme palette  (Option B — Clean Light + Blue Accent)
# ---------------------------------------------------------------------------
T_BG       = "#f5f7fa"   # window / frame background
T_FG       = "#1e2937"   # primary text
T_ACCENT   = "#1a56db"   # blue — Launch button, focus rings
T_BORDER   = "#c5d3e8"   # subtle blue-grey borders
T_LF_LBL   = "#2c3e6b"   # LabelFrame heading colour
T_HINT     = "#6b7a99"   # secondary / hint text
T_RED      = "#d93025"   # Stop button
T_TEAL     = "#0d9488"   # Open Portal button
T_HDR      = "#1a3a5c"   # header bar


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _safe_project_name(csv_path: str) -> str:
    """Derive a filesystem-safe project name from the CSV filename."""
    stem = os.path.splitext(os.path.basename(csv_path))[0]
    stem = re.sub(r"[^A-Za-z0-9_\-]", "_", stem)
    stem = re.sub(r"_+", "_", stem).strip("_")
    return stem or "project"


def _write_config(
    run_dir: str,
    project_name: str,
    csv_filename: str,
    pca_dims: int,
    resolution: float,
    port: int,
) -> str:
    """Write config.yaml into run_dir and return its path."""
    output_dir = f"{project_name}_results"
    content = (
        "# COMET Spatial Pipeline Configuration\n"
        "# Auto-generated by launch_pipeline_gui.py\n\n"
        f'name_of_project: "{project_name}"\n\n'
        f'HALO_data_file: "{csv_filename}"\n'
        'metadata_file: "metadata_markers.csv"\n\n'
        f'output_directory: "{output_dir}"\n\n'
        f"pca_dims: {pca_dims}\n"
        f"clustering_resolution: {resolution}\n"
        f"streamlit_port: {port}\n"
    )
    config_path = os.path.join(run_dir, "config.yaml")
    with open(config_path, "w", encoding="utf-8") as fh:
        fh.write(content)
    return config_path


def _popen_kwargs() -> dict:
    """Return platform-specific Popen kwargs (hide console window on Windows)."""
    kw: dict = {}
    if platform.system() == "Windows":
        si = subprocess.STARTUPINFO()
        si.dwFlags |= subprocess.STARTF_USESHOWWINDOW
        si.wShowWindow = subprocess.SW_HIDE
        kw["startupinfo"] = si
    return kw


def _docker_is_running() -> bool:
    """Return True if the Docker daemon responds."""
    try:
        r = subprocess.run(
            ["docker", "info"],
            capture_output=True,
            timeout=6,
            **_popen_kwargs(),
        )
        return r.returncode == 0
    except Exception:
        return False


def _find_docker_desktop() -> "str | None":
    """Return path to Docker Desktop.exe, or None if not found."""
    for path in _DOCKER_DESKTOP_CANDIDATES:
        if path and os.path.isfile(path):
            return path
    return None


# ---------------------------------------------------------------------------
# Main GUI
# ---------------------------------------------------------------------------

class CometLauncherApp(tk.Tk):
    def __init__(self) -> None:
        super().__init__()
        self.title("COMET Pipeline Launcher")
        self.resizable(True, True)
        self.minsize(740, 680)

        self._process: "subprocess.Popen | None" = None
        self._running = False
        self._browser_opened = False
        self._active_port = 8501

        # StringVars created early so _apply_theme can't fail
        self._csv_var  = tk.StringVar()
        self._name_var = tk.StringVar()
        self._out_var  = tk.StringVar()

        self._apply_theme()
        self._build_ui()
        self._center_window()

    # ── Theme ───────────────────────────────────────────────────────────────

    def _apply_theme(self) -> None:
        """Apply the Clean Light + Blue Accent visual theme (Option B)."""
        self.configure(bg=T_BG)
        s = ttk.Style(self)
        # 'clam' gives the most cross-platform control over colours
        s.theme_use("clam")

        # Base elements
        s.configure("TFrame",   background=T_BG)
        s.configure("TLabel",   background=T_BG, foreground=T_FG,
                    font=("Helvetica", 10))
        s.configure("TEntry",   fieldbackground="white",
                    bordercolor=T_BORDER, lightcolor=T_BORDER, darkcolor=T_BORDER,
                    padding=4)
        s.configure("TSpinbox", fieldbackground="white",
                    bordercolor=T_BORDER, lightcolor=T_BORDER, darkcolor=T_BORDER,
                    padding=4)
        s.map("TEntry",   bordercolor=[("focus", T_ACCENT)])
        s.map("TSpinbox", bordercolor=[("focus", T_ACCENT)])

        # LabelFrame — slate-blue heading, light border
        s.configure("TLabelframe",
                    background=T_BG,
                    bordercolor=T_BORDER,
                    lightcolor=T_BORDER,
                    darkcolor=T_BORDER,
                    relief="solid",
                    borderwidth=1)
        s.configure("TLabelframe.Label",
                    background=T_BG,
                    foreground=T_LF_LBL,
                    font=("Helvetica", 9, "bold"),
                    padding=(4, 0))

        # ── Custom button styles ─────────────────────────────────────────────
        _btn_base = dict(borderwidth=0, focusthickness=2,
                         focuscolor=T_BORDER, padding=(14, 7))

        # Accent — blue (Launch)
        s.configure("Accent.TButton", background=T_ACCENT, foreground="white",
                    font=("Helvetica", 10, "bold"), **_btn_base)
        s.map("Accent.TButton",
              background=[("active", "#1648c4"), ("disabled", "#a8bfe8")],
              foreground=[("disabled", "#dde5f5")])

        # Danger — red (Stop)
        s.configure("Danger.TButton", background=T_RED, foreground="white",
                    font=("Helvetica", 10), **_btn_base)
        s.map("Danger.TButton",
              background=[("active", "#b52a20"), ("disabled", "#d0d0d0")],
              foreground=[("disabled", "#a0a0a0")])

        # Teal (Open Portal)
        s.configure("Teal.TButton", background=T_TEAL, foreground="white",
                    font=("Helvetica", 10), **_btn_base)
        s.map("Teal.TButton",
              background=[("active", "#0a7a70"), ("disabled", "#d0d0d0")],
              foreground=[("disabled", "#a0a0a0")])

        # Muted — secondary action (Browse buttons)
        s.configure("Muted.TButton", background="#e2e8f0", foreground=T_FG,
                    font=("Helvetica", 10), **_btn_base)
        s.map("Muted.TButton",
              background=[("active", "#cbd5e1"), ("disabled", "#e9ecef")])

    # ── Layout ──────────────────────────────────────────────────────────────

    def _center_window(self) -> None:
        self.update_idletasks()
        w = max(self.winfo_reqwidth(), 740)
        h = max(self.winfo_reqheight(), 680)
        x = (self.winfo_screenwidth()  - w) // 2
        y = (self.winfo_screenheight() - h) // 2
        self.geometry(f"{w}x{h}+{x}+{y}")

    def _build_ui(self) -> None:
        row_pad = dict(padx=14, pady=6)

        # ── Header bar ──────────────────────────────────────────────────────
        hdr = tk.Frame(self, bg=T_HDR)
        hdr.pack(fill="x")

        tk.Label(
            hdr,
            text="  COMET  Spatial Pipeline Launcher",
            font=("Helvetica", 15, "bold"),
            fg="white", bg=T_HDR,
        ).pack(side="left", padx=14, pady=10)

        self._docker_lbl = tk.Label(
            hdr, text="⬤  Docker: checking…",
            font=("Helvetica", 9), fg="#8aafd4", bg=T_HDR,
        )
        self._docker_lbl.pack(side="right", padx=14)

        # ── Thin accent stripe under header ─────────────────────────────────
        tk.Frame(self, bg=T_ACCENT, height=3).pack(fill="x")

        # ── Scrollable main area ─────────────────────────────────────────────
        main = ttk.Frame(self, padding=(14, 10))
        main.pack(fill="both", expand=True)

        # ── Input CSV file ───────────────────────────────────────────────────
        file_lf = ttk.LabelFrame(main, text="Input Data File", padding=(10, 6))
        file_lf.pack(fill="x", **row_pad)

        ttk.Entry(file_lf, textvariable=self._csv_var).grid(
            row=0, column=0, sticky="ew", padx=(0, 8), ipady=2
        )
        ttk.Button(file_lf, text="Browse…",
                   command=self._browse_csv, style="Muted.TButton").grid(
            row=0, column=1
        )
        file_lf.columnconfigure(0, weight=1)

        ttk.Label(
            file_lf,
            text="Select the HALO or Horizon per-cell CSV export for this run.",
            foreground=T_HINT, font=("Helvetica", 9),
        ).grid(row=1, column=0, columnspan=2, sticky="w", pady=(3, 0))

        # ── Project name ─────────────────────────────────────────────────────
        proj_lf = ttk.LabelFrame(main, text="Project", padding=(10, 6))
        proj_lf.pack(fill="x", **row_pad)

        ttk.Label(proj_lf, text="Project name:").grid(row=0, column=0, sticky="w")
        ttk.Entry(proj_lf, textvariable=self._name_var).grid(
            row=0, column=1, sticky="ew", padx=(10, 0), ipady=2
        )
        ttk.Label(
            proj_lf,
            text="Auto-filled from the filename — edit freely.",
            foreground=T_HINT, font=("Helvetica", 9),
        ).grid(row=1, column=1, sticky="w", pady=(3, 0))
        proj_lf.columnconfigure(1, weight=1)

        # ── Output folder ────────────────────────────────────────────────────
        out_lf = ttk.LabelFrame(main, text="Output Folder", padding=(10, 6))
        out_lf.pack(fill="x", **row_pad)

        ttk.Entry(out_lf, textvariable=self._out_var).grid(
            row=0, column=0, sticky="ew", padx=(0, 8), ipady=2
        )
        ttk.Button(out_lf, text="Browse…",
                   command=self._browse_out, style="Muted.TButton").grid(
            row=0, column=1
        )
        out_lf.columnconfigure(0, weight=1)

        ttk.Label(
            out_lf,
            text="Results folder will be created here. Defaults to the same folder as the CSV.",
            foreground=T_HINT, font=("Helvetica", 9),
        ).grid(row=1, column=0, columnspan=2, sticky="w", pady=(3, 0))

        # ── Pipeline parameters ──────────────────────────────────────────────
        param_lf = ttk.LabelFrame(main, text="Pipeline Parameters", padding=(10, 6))
        param_lf.pack(fill="x", **row_pad)

        # Row 0 — PCA dims
        ttk.Label(param_lf, text="PCA dimensions:").grid(
            row=0, column=0, sticky="w")
        self._pca_var = tk.IntVar(value=8)
        ttk.Spinbox(
            param_lf, from_=1, to=50, textvariable=self._pca_var, width=7
        ).grid(row=0, column=1, sticky="w", padx=(10, 16))
        ttk.Label(param_lf, text="5–15 is typical for 20–40 markers",
                  foreground=T_HINT, font=("Helvetica", 9)).grid(
            row=0, column=2, sticky="w")

        # Row 1 — Clustering resolution
        ttk.Label(param_lf, text="Clustering resolution:").grid(
            row=1, column=0, sticky="w", pady=(8, 0))
        self._res_var = tk.StringVar(value="0.5")
        ttk.Entry(param_lf, textvariable=self._res_var, width=7).grid(
            row=1, column=1, sticky="w", padx=(10, 16), pady=(8, 0), ipady=2)
        ttk.Label(param_lf, text="Higher → more clusters.  Try 0.2 – 1.0",
                  foreground=T_HINT, font=("Helvetica", 9)).grid(
            row=1, column=2, sticky="w", pady=(8, 0))

        # Row 2 — Port
        ttk.Label(param_lf, text="Annotation portal port:").grid(
            row=2, column=0, sticky="w", pady=(8, 0))
        self._port_var = tk.IntVar(value=8501)
        ttk.Spinbox(
            param_lf, from_=1024, to=65535, textvariable=self._port_var, width=7
        ).grid(row=2, column=1, sticky="w", padx=(10, 16), pady=(8, 0))
        ttk.Label(param_lf, text="Change if 8501 is already in use on this PC",
                  foreground=T_HINT, font=("Helvetica", 9)).grid(
            row=2, column=2, sticky="w", pady=(8, 0))

        param_lf.columnconfigure(2, weight=1)

        # ── Pipeline log ─────────────────────────────────────────────────────
        log_lf = ttk.LabelFrame(main, text="Pipeline Log", padding=(10, 6))
        log_lf.pack(fill="both", expand=True, **row_pad)

        self._log = scrolledtext.ScrolledText(
            log_lf,
            height=12,
            state="disabled",
            font=("Consolas", 11),
            wrap="word",
            bg="#1e2637",
            fg="#cdd6f4",
            insertbackground="#cdd6f4",
            cursor="arrow",
            selectbackground="#3d5a9e",
            selectforeground="#ffffff",
            relief="flat",
            borderwidth=0,
            padx=8,
            pady=6,
        )
        self._log.pack(fill="both", expand=True)

        # ── Button row ───────────────────────────────────────────────────────
        btn_frame = ttk.Frame(main)
        btn_frame.pack(fill="x", pady=(8, 4))

        self._launch_btn = ttk.Button(
            btn_frame, text="▶  Launch Pipeline",
            command=self._on_launch, style="Accent.TButton",
        )
        self._launch_btn.pack(side="left", padx=(0, 8))

        self._stop_btn = ttk.Button(
            btn_frame, text="■  Stop",
            command=self._on_stop, style="Danger.TButton", state="disabled",
        )
        self._stop_btn.pack(side="left")

        self._portal_btn = ttk.Button(
            btn_frame, text="🌐  Open Annotation Portal",
            command=self._open_portal, style="Teal.TButton", state="disabled",
        )
        self._portal_btn.pack(side="right")

        # Trace CSV path changes → auto-fill project name + output folder
        self._csv_var.trace_add("write", self._on_csv_change)

        # Check Docker status in the background on startup
        threading.Thread(target=self._check_docker_status, daemon=True).start()

    # ── Docker status check on startup ──────────────────────────────────────

    def _check_docker_status(self) -> None:
        if _docker_is_running():
            self.after(0, lambda: self._docker_lbl.configure(
                text="⬤  Docker: running", fg="#5fba7d"
            ))
        else:
            self.after(0, lambda: self._docker_lbl.configure(
                text="⬤  Docker: not running", fg="#e06c75"
            ))

    # ── Event handlers ───────────────────────────────────────────────────────

    def _on_csv_change(self, *_) -> None:
        path = self._csv_var.get()
        if path and os.path.isfile(path):
            self._name_var.set(_safe_project_name(path))
            # Auto-fill output folder only if the user hasn't already picked one
            if not self._out_var.get():
                self._out_var.set(os.path.dirname(os.path.abspath(path)))

    def _browse_csv(self) -> None:
        path = filedialog.askopenfilename(
            title="Select HALO / Horizon CSV export",
            filetypes=[("CSV files", "*.csv"), ("All files", "*.*")],
        )
        if path:
            self._csv_var.set(os.path.normpath(path))

    def _browse_out(self) -> None:
        initial = self._out_var.get() or None
        folder = filedialog.askdirectory(
            title="Choose output folder for results",
            initialdir=initial,
        )
        if folder:
            self._out_var.set(os.path.normpath(folder))

    def _on_launch(self) -> None:
        csv_path = self._csv_var.get().strip()
        if not csv_path or not os.path.isfile(csv_path):
            messagebox.showerror("No input file",
                                 "Please select a valid CSV file before launching.")
            return

        project_name = self._name_var.get().strip()
        if not project_name:
            messagebox.showerror("No project name", "Please enter a project name.")
            return

        try:
            resolution = float(self._res_var.get())
            if resolution <= 0:
                raise ValueError
        except ValueError:
            messagebox.showerror(
                "Invalid resolution",
                "Clustering resolution must be a positive number (e.g. 0.5).",
            )
            return

        pca_dims = int(self._pca_var.get())
        port     = int(self._port_var.get())

        if not os.path.isfile(COMPOSE_FILE):
            messagebox.showerror(
                "docker-compose.yml not found",
                f"Expected file at:\n{COMPOSE_FILE}\n\n"
                "Make sure you are running from the correct pipeline folder.",
            )
            return

        # Determine run / output folder
        csv_abs    = os.path.abspath(csv_path)
        out_folder = self._out_var.get().strip()
        if not out_folder:
            out_folder = os.path.dirname(csv_abs)

        run_dir = out_folder
        os.makedirs(run_dir, exist_ok=True)

        # If the CSV lives elsewhere, copy it so Docker can see it under /data
        csv_in_run  = os.path.join(run_dir, os.path.basename(csv_abs))
        needs_copy  = os.path.abspath(csv_in_run) != csv_abs

        self._log_clear()

        if needs_copy:
            self._log_write(
                f"[COMET] Copying data file to output folder…\n"
                f"        {csv_abs}\n"
                f"     →  {csv_in_run}\n"
            )
            try:
                shutil.copy2(csv_abs, csv_in_run)
                self._log_write("[COMET] Copy done.\n\n")
            except OSError as exc:
                messagebox.showerror("File copy failed", str(exc))
                return

        csv_filename = os.path.basename(csv_abs)

        try:
            cfg = _write_config(
                run_dir, project_name, csv_filename,
                pca_dims, resolution, port,
            )
        except OSError as exc:
            messagebox.showerror("Config write failed", str(exc))
            return

        self._log_write(f"[COMET] Config written → {cfg}\n")
        self._log_write(f"[COMET] Run folder     → {run_dir}\n\n")

        self._launch_btn.configure(state="disabled")
        self._stop_btn.configure(state="normal")
        self._portal_btn.configure(state="disabled")
        self._browser_opened = False
        self._running        = True
        self._active_port    = port

        threading.Thread(
            target=self._docker_thread, args=(run_dir, port), daemon=True
        ).start()

    def _on_stop(self) -> None:
        if self._process and self._running:
            self._log_write("\n[COMET] Stopping…\n")
            try:
                self._process.terminate()
            except Exception:
                pass

    def _open_portal(self) -> None:
        webbrowser.open(f"http://localhost:{self._active_port}")

    # ── Docker thread ────────────────────────────────────────────────────────

    def _docker_thread(self, run_dir: str, port: int) -> None:
        # ── Step 1: ensure Docker is running ────────────────────────────────
        if not _docker_is_running():
            self._log_write("[COMET] Docker is not running — starting Docker Desktop…\n")
            self.after(0, lambda: self._docker_lbl.configure(
                text="⬤  Docker: starting…", fg="#e5c07b"
            ))

            exe = _find_docker_desktop()
            if not exe:
                self._log_write(
                    "[ERROR] Docker Desktop not found.\n"
                    "Please install it from https://www.docker.com/products/docker-desktop/\n"
                    "then try again.\n"
                )
                self._finish(None)
                return

            try:
                subprocess.Popen([exe], **_popen_kwargs())
            except Exception as exc:
                self._log_write(f"[ERROR] Could not launch Docker Desktop: {exc}\n")
                self._finish(None)
                return

            self._log_write("[COMET] Waiting for Docker to be ready")
            deadline = time.time() + DOCKER_READY_TIMEOUT
            ready = False
            while time.time() < deadline:
                time.sleep(3)
                self._log_write(".")
                if _docker_is_running():
                    ready = True
                    break

            if not ready:
                self._log_write(
                    f"\n[ERROR] Docker did not start within {DOCKER_READY_TIMEOUT}s.\n"
                    "Please open Docker Desktop manually and wait until it shows\n"
                    "'Docker Desktop is running', then click Launch again.\n"
                )
                self._finish(None)
                return

            self._log_write("\n[COMET] Docker is ready.\n\n")
            self.after(0, lambda: self._docker_lbl.configure(
                text="⬤  Docker: running", fg="#5fba7d"
            ))

        # ── Step 2: run the pipeline ─────────────────────────────────────────
        self._log_write("[COMET] Starting pipeline…\n\n")

        env = os.environ.copy()
        env["RUN_DIR"]        = run_dir
        env["STREAMLIT_PORT"] = str(port)

        cmd = ["docker", "compose", "-f", COMPOSE_FILE, "up", "--build"]

        try:
            self._process = subprocess.Popen(
                cmd,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True,
                env=env,
                cwd=SCRIPT_DIR,
                bufsize=1,
                **_popen_kwargs(),
            )
        except FileNotFoundError:
            self._log_write(
                "[ERROR] 'docker' command not found.\n"
                "Please install Docker Desktop from https://www.docker.com/\n"
            )
            self._finish(None)
            return
        except Exception as exc:
            self._log_write(f"[ERROR] Could not start Docker: {exc}\n")
            self._finish(None)
            return

        streamlit_ready_re = re.compile(
            r"(Local URL|Network URL|You can now view|Streamlit app running)",
            re.IGNORECASE,
        )

        for line in self._process.stdout:
            self._log_write(line)
            if not self._browser_opened and streamlit_ready_re.search(line):
                self._browser_opened = True
                url = f"http://localhost:{port}"
                self._log_write(f"[COMET] Annotation portal ready → {url}\n")
                self.after(0, lambda: self._portal_btn.configure(state="normal"))
                webbrowser.open(url)

        retcode = self._process.wait()
        self._finish(retcode)

    def _finish(self, retcode: "int | None") -> None:
        self._running = False
        self._process = None
        threading.Thread(target=self._check_docker_status, daemon=True).start()

        def _ui() -> None:
            self._launch_btn.configure(state="normal")
            self._stop_btn.configure(state="disabled")
            if retcode == 0:
                self._log_write("\n[COMET] Pipeline finished successfully.\n")
                messagebox.showinfo("Done", "The COMET pipeline completed successfully!")
            elif retcode is not None:
                self._log_write(
                    f"\n[COMET] Pipeline exited with code {retcode}.\n"
                    "Check the log above for details.\n"
                )

        self.after(0, _ui)

    # ── Log helpers ──────────────────────────────────────────────────────────

    def _log_write(self, text: str) -> None:
        def _do():
            self._log.configure(state="normal")
            self._log.insert("end", text)
            self._log.see("end")
            self._log.configure(state="disabled")
        self.after(0, _do)

    def _log_clear(self) -> None:
        self._log.configure(state="normal")
        self._log.delete("1.0", "end")
        self._log.configure(state="disabled")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    app = CometLauncherApp()
    app.mainloop()


if __name__ == "__main__":
    main()
